name: Build Free APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova App Setup
        run: |
          cordova create build-folder com.mycode.customkeyboard "My Keyboard"
          rm -rf build-folder/www/*
          cp index.html build-folder/www/
          cp config.xml build-folder/
          cd build-folder
          cordova platform add android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK
        run: |
          cd build-folder
          cordova build android --debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: MyKeyboard-APK
          path: build-folder/platforms/android/app/build/outputs/apk/debug/app-debug.apk
